/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hobot_otacli_OTACli */

#ifndef _Included_com_hobot_otacli_OTACli
#define _Included_com_hobot_otacli_OTACli
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hobot_otacli_OTACli
 * Method:    initOtaCli
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_hobot_otacli_OTACli_initOtaCli
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_hobot_otacli_OTACli
 * Method:    authDevice
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_hobot_otacli_OTACli_authDevice
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_hobot_otacli_OTACli
 * Method:    reportDeviceAttrs
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_hobot_otacli_OTACli_reportDeviceAttrs
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_hobot_otacli_OTACli
 * Method:    reportDeployStatus
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_hobot_otacli_OTACli_reportDeployStatus
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_hobot_otacli_OTACli
 * Method:    reportDeployLogs
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_hobot_otacli_OTACli_reportDeployLogs
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_hobot_otacli_OTACli
 * Method:    queryUpdatorPackage
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_hobot_otacli_OTACli_queryUpdatorPackage
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_hobot_otacli_OTACli
 * Method:    downLoadUpdatorPackage
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_hobot_otacli_OTACli_downLoadUpdatorPackage
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_hobot_otacli_OTACli
 * Method:    setCallBack
 * Signature: (Lcom/hobot/otacli/OTACli;)I
 */
JNIEXPORT jint JNICALL Java_com_hobot_otacli_OTACli_setCallBack
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
